import React, { useEffect, useState } from "react";
import {
  ArrowLeft,
  BrainCircuit,
  CheckCircle2,
  Clock3,
  Database,
  ShieldCheck,
  TriangleAlert
} from "lucide-react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import ScoreBar from "../components/ScoreBar";
import { api } from "../services/api";

export default function ResearchDashboard() {

  const [data, setData] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    let mounted = true;

    api.get("/analytics/model")
      .then(response => {
        if (mounted) setData(response);
      })
      .catch(err => {
        if (mounted) setError(err.message);
      });

    return () => {
      mounted = false;
    };
  }, []);

  return (
    <main className="app-page">

      <Navbar />

      <div className="page-wrap">

        <Link to="/dashboard" className="back-link">
          <ArrowLeft size={15} />
          Dashboard
        </Link>

        <section className="module-head">
          <div className="eyebrow">
            <BrainCircuit size={14} />
            RESEARCH / MODEL EVIDENCE
          </div>

          <h1>
            Make the intelligence auditable.
          </h1>

          <p>
            This panel displays measured model evidence only.
            Metrics remain explicitly marked as unevaluated until
            a held-out test set is processed.
          </p>
        </section>

        {error && (
          <div className="error-box">
            {error}
          </div>
        )}

        {data && (
          <>

            <section className="research-status glass">

              <div>
                <div className="eyebrow">
                  EVIDENCE STATUS
                </div>

                <h2>
                  {data.evaluated
                    ? "Evaluation available"
                    : "Evaluation not yet performed"
                  }
                </h2>

                <p>
                  {data.evaluated
                    ? "The metrics below are loaded from the backend evaluation artifact."
                    : "No model_metrics.json is present. Run the held-out test evaluation before making performance claims."
                  }
                </p>
              </div>

              {data.evaluated ? (
                <CheckCircle2 size={30} />
              ) : (
                <TriangleAlert size={30} />
              )}

            </section>

            <div className="research-grid">

              <article className="metric-card glass">
                <Database size={18} />
                <strong>
                  {data.model?.model_file || "—"}
                </strong>
                <span>Model artifact</span>
              </article>

              <article className="metric-card glass">
                <BrainCircuit size={18} />
                <strong>
                  {data.model?.output_shape
                    ? data.model.output_shape.join(" × ")
                    : "—"
                  }
                </strong>
                <span>Output interface</span>
              </article>

              <article className="metric-card glass">
                <ShieldCheck size={18} />
                <strong>
                  {data.model?.face_detector
                    ? "Enabled"
                    : "Fallback"
                  }
                </strong>
                <span>Face preprocessing</span>
              </article>

              <article className="metric-card glass">
                <Clock3 size={18} />
                <strong>
                  {data.metrics?.metrics?.mean_inference_ms !== undefined
                    ? `${data.metrics.metrics.mean_inference_ms} ms`
                    : "—"
                  }
                </strong>
                <span>Measured inference</span>
              </article>

            </div>

            {data.evaluated && data.metrics?.metrics && (
              <section className="research-results">

                <div className="section-heading">
                  <div>
                    <div className="eyebrow">
                      HELD-OUT PERFORMANCE
                    </div>
                    <h2>
                      Measured metrics.
                    </h2>
                  </div>
                  <p>
                    Values shown here are generated by the
                    evaluation script—not hard-coded.
                  </p>
                </div>

                <div className="research-metrics glass">

                  <ScoreBar
                    label="Accuracy"
                    value={data.metrics.metrics.accuracy * 100}
                  />

                  <ScoreBar
                    label="Macro precision"
                    value={data.metrics.metrics.macro_precision * 100}
                  />

                  <ScoreBar
                    label="Macro recall"
                    value={data.metrics.metrics.macro_recall * 100}
                  />

                  <ScoreBar
                    label="Macro F1"
                    value={data.metrics.metrics.macro_f1 * 100}
                  />

                  <div className="confusion-card">
                    <div className="eyebrow">
                      CONFUSION MATRIX
                    </div>

                    <div className="confusion-scroll">

                      <table>
                        <thead>
                          <tr>
                            <th>True ↓ / Pred →</th>
                            {data.metrics.confusion_matrix.labels.map(
                              label => (
                                <th key={label}>
                                  {label}
                                </th>
                              )
                            )}
                          </tr>
                        </thead>

                        <tbody>
                          {data.metrics.confusion_matrix.matrix.map(
                            (row, rowIndex) => (
                              <tr key={rowIndex}>
                                <th>
                                  {data.metrics.confusion_matrix.labels[rowIndex]}
                                </th>

                                {row.map(
                                  (value, columnIndex) => (
                                    <td key={columnIndex}>
                                      {value}
                                    </td>
                                  )
                                )}
                              </tr>
                            )
                          )}
                        </tbody>

                      </table>

                    </div>
                  </div>

                </div>

              </section>
            )}

          </>
        )}

      </div>
    </main>
  );
}
